services:
    sonata.admin.livebroadcast:
        class: Martin1982\LiveBroadcastBundle\Admin\LiveBroadcastAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Live Broadcasts"

        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\LiveBroadcast
            - ~
        calls:
            - [ setTranslationDomain, [LiveBroadcastBundle]]
