services:
    sonata.admin.livebroadcast:
        class: Martin1982\LiveBroadcastBundle\Admin\LiveBroadcastAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Live Broadcasts"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\LiveBroadcast
            - ~
        calls:
            - [ setTranslationDomain, [LiveBroadcastBundle]]
            - [ setBroadcastManager, ["@live.broadcast.broadcastmanager"]]
            - [ setThumbnailListener, ["@live.broadcast.thumbnail.listener"]]
            - [ setObjectManager, ["@doctrine"]]

    sonata.admin.channel:
        class: Martin1982\LiveBroadcastBundle\Admin\ChannelAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Channels"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\Channel\AbstractChannel
            - LiveBroadcastBundle:CRUD
        calls:
            - [setSubclassConfigs, ["%livebroadcast.config%"]]
            - [setConfiguredSubclasses, [ { "Twitch": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelTwitch, "Facebook": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelFacebook, "YouTube": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelYouTube, "Ustream": Martin1982\LiveBroadcastBundle\Entity\Channel\ChannelUstream } ] ]

    sonata.admin.streaminput:
        class: Martin1982\LiveBroadcastBundle\Admin\InputAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Live"
              label: "Inputs"
        arguments:
            - ~
            - Martin1982\LiveBroadcastBundle\Entity\Media\AbstractMedia
            - ~
        calls:
            - [setSubClasses, [ { "File": Martin1982\LiveBroadcastBundle\Entity\Media\MediaFile, "URL": Martin1982\LiveBroadcastBundle\Entity\Media\MediaUrl, "RTMP": Martin1982\LiveBroadcastBundle\Entity\Media\MediaRtmp } ] ]

    sonata.block.service.youtubeauth:
        class: Martin1982\LiveBroadcastBundle\Admin\Block\YouTubeBlockService
        arguments:
            - sonata.block.service.youtubeauth
            - "@templating"
            - "@live.broadcast.channelapi.client.google"
            - "@request_stack"
        tags:
            - { name: sonata.block }

    sonata.block.service.facebookauth:
        class: Martin1982\LiveBroadcastBundle\Admin\Block\FacebookBlockService
        arguments:
            - sonata.block.service.facebookauth
            - "@templating"
            - "@live.broadcast.facebookapi.service"
            - "@sonata.admin.channel"
        tags:
            - { name: sonata.block }
