services:
  live.broadcast.streamoutput.service:
    class: Martin1982\LiveBroadcastBundle\Service\StreamOutputService

  live.broadcast.can_stream_to_channel_validator:
    class: Martin1982\LiveBroadcastBundle\Validator\Constraints\CanStreamToChannelValidator
    arguments:
      - "@live.broadcast.streamoutput.service"
    tags:
      - { name: validator.constraint_validator }

# Individual output services
  live.broadcast.output.youtube:
    arguments:
      - "@live.broadcast.youtubeapi.service"
    class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputYouTube
    tags:
      - { name: live.broadcast.output, platform: 'YouTube' }
  live.broadcast.output.facebook:
    arguments:
      - "@live.broadcast.facebookapi.service"
    class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputFacebook
    tags:
      - { name: live.broadcast.output, platform: 'Facebook' }
  live.broadcast.output.twitch:
    class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputTwitch
    tags:
      - { name: live.broadcast.output, platform: 'Twitch' }
