services:
  live.broadcast.scheduler.commands:
    class: Martin1982\LiveBroadcastBundle\Broadcaster\AbstractSchedulerCommands
    factory: [Martin1982\LiveBroadcastBundle\Broadcaster\SchedulerCommandsDetector, createSchedulerCommands]
    arguments:
      - "%kernel.environment%"
  live.broadcast.scheduler:
    class: Martin1982\LiveBroadcastBundle\Broadcaster\Scheduler
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@live.broadcast.scheduler.commands"
      - "@logger"
    tags: [{ name: monolog.logger, channel: livebroadcaster }]
