services:
  live.broadcast.scheduler.commands:
    class: Martin1982\LiveBroadcastBundle\Broadcaster\AbstractSchedulerCommands
    factory: [Martin1982\LiveBroadcastBundle\Broadcaster\SchedulerCommandsDetector, createSchedulerCommands]
    arguments:
      - "%kernel.environment%"
  live.broadcast.scheduler:
    class: Martin1982\LiveBroadcastBundle\Broadcaster\Scheduler
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@live.broadcast.scheduler.commands"
      - "@live.broadcast.streamoutput.service"
      - "@event_dispatcher"
      - "@logger"
    tags: [{ name: monolog.logger, channel: livebroadcaster }]
  live.broadcast.facebook_pre_broadcast_listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\FacebookPreBroadcastListener
      arguments: ["@live.broadcast.facebooklive.service"]
      tags:
          - { name: kernel.event_subscriber }
  live.broadcast.facebooklive.service:
      class: Martin1982\LiveBroadcastBundle\Service\FacebookLiveService
      arguments: ["%fb_app_id%", "%fb_app_secret%"]
  live.broadcast.streamoutput.service:
      class: Martin1982\LiveBroadcastBundle\Service\StreamOutputService
  live.broadcast.output.facebook:
    class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputFacebook
    tags:
        - { name: live.broadcast.output, platform: 'Facebook' }
  live.broadcast.output.twitch:
    class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputTwitch
    tags:
        - { name: live.broadcast.output, platform: 'Twitch' }
  live.broadcast.output.ustream:
    class: Martin1982\LiveBroadcastBundle\Service\StreamOutput\OutputUstream
    tags:
        - { name: live.broadcast.output, platform: 'Ustream' }
