language: php
dist: xenial

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.1
    - 7.2

matrix:
    include:
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-lowest"
    fast_finish: true

install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi
    - composer update --no-interaction --prefer-source $COMPOSER_FLAGS

script:
    - php ./vendor/bin/phpunit --coverage-text --colors
    - php ./vendor/bin/phpcs --standard=./vendor/escapestudios/symfony2-coding-standard/Symfony/ Admin/ Broadcaster/ Command/ Controller/ DependencyInjection/ Entity/ EventListener/ Exception/ Resources/ Service/ Tests/ LiveBroadcastBundle.php
